name: Auto Deploy SaveinCloud

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  ENV_NAME: ${{ secrets.JELASTIC_ENV_NAME }}
  REGION: "vz7"
  MANIFEST_URL: "https://raw.githubusercontent.com/carriel2/jelastic-demo/main/manifest.jps"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Jelastic CLI
        run: |
          curl -s ftp://ftp.jelastic.com/pub/cli/jelastic-cli-installer.sh | bash
          
      - name: Authenticate
        run: |
          /home/runner/jelastic/users/authentication/signin \
            --login "${{ secrets.JELASTIC_EMAIL }}" \
            --password "${{ secrets.JELASTIC_PASSWORD }}" \
            --platformUrl "${{ secrets.JELASTIC_API_URL }}" \
            --silent true
            
      - name: Check Logic (List & JQ)
        id: check-env
        run: |
          # Obtém a lista e usa JQ para verificar se o envName existe no array de objetos
          EXISTS=$(/home/runner/jelastic/environment/control/getenvs --silent true | jq -r '.infos[] | select(.env.envName=="${{ env.ENV_NAME }}") | .env.envName')
          
          if [ "$EXISTS" == "${{ env.ENV_NAME }}" ]; then
            echo "status=exists" >> $GITHUB_OUTPUT
            echo "Environment Found: ${{ env.ENV_NAME }}"
          else
            echo "status=missing" >> $GITHUB_OUTPUT
            echo "Environment not fount. Creating"
          fi

      - name: Create Environment
        if: steps.check-env.outputs.status == 'missing'
        run: |
          /home/runner/jelastic/marketplace/jps/install \
            --jps "${{ env.MANIFEST_URL }}" \
            --envName ${{ env.ENV_NAME }} \
            --region ${{ env.REGION }} \
            --settings '{"jelastic_email":"${{ secrets.JELASTIC_EMAIL }}"}' \
            --silent true

      - name: Update Environment
        if: steps.check-env.outputs.status == 'exists'
        run: |
          # Removi as quebras de linha dentro do commandList para evitar erro de parse no shell
          /home/runner/jelastic/environment/control/execcmdbygroup \
            --envName "${{ env.ENV_NAME }}" \
            --nodeGroup cp \
            --commandList '[{"command": "cd /app/repo && git pull && docker-compose up -d --build", "params": ""}]' \
            --silent true